name: Publish to npm

on:
  push:
    branches:
      - master
    paths:
      - 'package.json'

jobs:
  test:
    uses: ./.github/workflows/test.yml

  get-version:
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.get_current_version.outputs.version }}
      last_version: ${{ steps.get_last_version.outputs.version }}
      token_exists: ${{ steps.check_token.outputs.token_exists }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get current version from package.json
        id: get_current_version
        run: |
          echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Get version from the last push
        id: get_last_version
        run: |
          git checkout ${{ github.event.before }} -- package.json
          echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Check if NPM_TOKEN exists
        id: check_token
        run: |
          if [ -n "${{ secrets.NPM_TOKEN }}" ]; then echo "token_exists=true"; else echo "token_exists=false"; fi >> $GITHUB_OUTPUT

  npm-publish:
    needs:
      - test
      - get-version
    runs-on: ubuntu-latest
    if: needs.get-version.outputs.current_version != needs.get-version.outputs.last_version && needs.get-version.outputs.token_exists == 'true'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
